language: node_js
node_js:
- '6'
sudo: false
script: npm run $COMMAND
before_script:
- npm run lint
env:
  matrix:
  - COMMAND=test
  - COMMAND=test-browser
matrix:
  include:
    - node_js: "4"
      services: docker
      env: CLIENT=node COMMAND=test
    - node_js: "7"
      services: docker
      env: CLIENT=node COMMAND=test
branches:
  only:
  - master
